[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-docx>=1.1.2",
    "reportlab>=4.3.1",
    "streamlit>=1.43.0",
]
